#!/usr/bin/env bash
set -euo pipefail

# Run from repo root.
cd "$(dirname "$0")/.."

out_dir="assets/flags"
out_file="${out_dir}/ATTRIBUTION.md"
mkdir -p "$out_dir"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: missing dependency: $1" >&2
    exit 1
  }
}

need_cmd curl
need_cmd jq
need_cmd python3

# stateCode -> Wikimedia Commons "File:" name (without /wiki/File:)
declare -A files=(
  [AL]="Flag_of_Alabama.svg"
  [AK]="Flag_of_Alaska.svg"
  [AZ]="Flag_of_Arizona.svg"
  [AR]="Flag_of_Arkansas.svg"
  [CA]="Flag_of_California.svg"
  [CO]="Flag_of_Colorado.svg"
  [CT]="Flag_of_Connecticut.svg"
  [DE]="Flag_of_Delaware.svg"
  [FL]="Flag_of_Florida.svg"
  [GA]="Flag_of_Georgia_(U.S._state).svg"
  [HI]="Flag_of_Hawaii.svg"
  [ID]="Flag_of_Idaho.svg"
  [IL]="Flag_of_Illinois.svg"
  [IN]="Flag_of_Indiana.svg"
  [IA]="Flag_of_Iowa.svg"
  [KS]="Flag_of_Kansas.svg"
  [KY]="Flag_of_Kentucky.svg"
  [LA]="Flag_of_Louisiana.svg"
  [ME]="Flag_of_Maine.svg"
  [MD]="Flag_of_Maryland.svg"
  [MA]="Flag_of_Massachusetts.svg"
  [MI]="Flag_of_Michigan.svg"
  [MN]="Flag_of_Minnesota.svg"
  [MS]="Flag_of_Mississippi.svg"
  [MO]="Flag_of_Missouri.svg"
  [MT]="Flag_of_Montana.svg"
  [NE]="Flag_of_Nebraska.svg"
  [NV]="Flag_of_Nevada.svg"
  [NH]="Flag_of_New_Hampshire.svg"
  [NJ]="Flag_of_New_Jersey.svg"
  [NM]="Flag_of_New_Mexico.svg"
  [NY]="Flag_of_New_York.svg"
  [NC]="Flag_of_North_Carolina.svg"
  [ND]="Flag_of_North_Dakota.svg"
  [OH]="Flag_of_Ohio.svg"
  [OK]="Flag_of_Oklahoma.svg"
  [OR]="Flag_of_Oregon.svg"
  [PA]="Flag_of_Pennsylvania.svg"
  [RI]="Flag_of_Rhode_Island.svg"
  [SC]="Flag_of_South_Carolina.svg"
  [SD]="Flag_of_South_Dakota.svg"
  [TN]="Flag_of_Tennessee.svg"
  [TX]="Flag_of_Texas.svg"
  [UT]="Flag_of_Utah.svg"
  [VT]="Flag_of_Vermont.svg"
  [VA]="Flag_of_Virginia.svg"
  [WA]="Flag_of_Washington.svg"
  [WV]="Flag_of_West_Virginia.svg"
  [WI]="Flag_of_Wisconsin.svg"
  [WY]="Flag_of_Wyoming.svg"
)

fetch_commons_json() {
  local file="$1"
  curl -fsSL "https://commons.wikimedia.org/w/api.php" \
    --get \
    --data-urlencode "action=query" \
    --data-urlencode "format=json" \
    --data-urlencode "formatversion=2" \
    --data-urlencode "prop=imageinfo" \
    --data-urlencode "titles=File:${file}" \
    --data-urlencode "iiprop=extmetadata|url" \
    --data-urlencode "iiurlwidth=1"
}

extract_field() {
  # Usage: extract_field "$json" "Artist"
  python3 - "$2" <<'PY'
import json, sys
data = json.load(sys.stdin)
field = sys.argv[1]
pages = data.get("query", {}).get("pages", [])
if not pages:
  print("")
  sys.exit(0)
ii = (pages[0].get("imageinfo") or [])
meta = (ii[0].get("extmetadata") or {}) if ii else {}
val = meta.get(field, {}).get("value", "")
print(val)
PY
}

strip_html() {
  python3 - <<'PY'
import re, sys
s = sys.stdin.read()
s = s.replace("\r", "")
# crude but good enough for Commons extmetadata snippets
s = re.sub(r"<br\s*/?>", "\n", s, flags=re.I)
s = re.sub(r"</p\s*>", "\n", s, flags=re.I)
s = re.sub(r"<[^>]+>", "", s)
s = re.sub(r"\n{3,}", "\n\n", s)
print(s.strip())
PY
}

tmp="$(mktemp -d)"
cleanup() { rm -rf "$tmp"; }
trap cleanup EXIT

{
  echo "# Flag attribution"
  echo
  echo "This file is generated by \`scripts/generate-flag-attribution.sh\`."
  echo
  echo "Source collection: https://commons.wikimedia.org/wiki/Flags_of_the_U.S._states"
  echo
  echo "Each entry lists the metadata provided by Wikimedia Commons (author/license may vary per file)."
  echo
} >"$out_file"

# stable order
codes_sorted="$(printf '%s\n' "${!files[@]}" | sort)"

for code in $codes_sorted; do
  file="${files[$code]}"
  echo "==> ${code} (${file})"

  json_path="${tmp}/${code}.json"
  fetch_commons_json "$file" >"$json_path"

  # Prefer commonly-available fields from extmetadata
  artist="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.Artist.value // ""' "$json_path" | strip_html || true)"
  author="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.Author.value // ""' "$json_path" | strip_html || true)"
  credit="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.Credit.value // ""' "$json_path" | strip_html || true)"
  license_short="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.LicenseShortName.value // ""' "$json_path" | strip_html || true)"
  license="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.License.value // ""' "$json_path" | strip_html || true)"
  usage_terms="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.UsageTerms.value // ""' "$json_path" | strip_html || true)"
  attribution_req="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.AttributionRequired.value // ""' "$json_path" | strip_html || true)"
  source="$(jq -r '.query.pages[0].imageinfo[0].extmetadata.ImageDescription.value // ""' "$json_path" >/dev/null 2>&1 || true; echo "" )"

  page_url="https://commons.wikimedia.org/wiki/File:${file}"
  raw_url="$(jq -r '.query.pages[0].imageinfo[0].url // ""' "$json_path")"

  {
    echo
    echo "## ${code}.svg"
    echo
    echo "- Source page: ${page_url}"
    if [[ -n "$raw_url" ]]; then
      echo "- Direct file URL: ${raw_url}"
    fi

    # Prefer Artist; fallback to Author.
    if [[ -n "$artist" ]]; then
      echo "- Author/Artist: ${artist}"
    elif [[ -n "$author" ]]; then
      echo "- Author: ${author}"
    else
      echo "- Author: (not provided in extmetadata)"
    fi

    if [[ -n "$credit" ]]; then
      echo "- Credit: ${credit}"
    fi

    if [[ -n "$license_short" ]]; then
      echo "- License (short): ${license_short}"
    fi
    if [[ -n "$license" ]]; then
      echo "- License: ${license}"
    elif [[ -n "$usage_terms" ]]; then
      echo "- Usage terms: ${usage_terms}"
    else
      echo "- License/usage terms: (not provided in extmetadata)"
    fi

    if [[ -n "$attribution_req" ]]; then
      echo "- Attribution required: ${attribution_req}"
    fi

    echo "- Modifications: none"
  } >>"$out_file"
done

echo
echo "Wrote: ${out_file}"
echo "Note: verify any special notes on the Commons file pages (some flags may have extra trademark/government-use notes)."
